/*******************************************************************************
    Testing program for the import_xfoil_polars() function

    How to run:
    gcc 02_test_import_xfoil_polars.c -o 02_test_import_xfoil_polars -lm -Wall -Wextra
    ./02_test_import_xfoil_polars

    Author: Andrea Pavan
    License: MIT
*******************************************************************************/
#include <stdio.h>
#include "../src/qprop.c"

int main() {
    //test #1: import FX63-120 polar, generated by XFOIL
    Polar* polar1 = read_xfoil_polar_from_file("02_airfoil_polar_FX63-120_Re0.300_M0.00_N9.0.txt");
    if (polar1->Re == 300000
                && polar1->alpha[2] == deg2rad(2.000)
                && polar1->CL[0] == 0.8022
                && polar1->CD[polar1->size-1]==0.06283
                && polar1->size==14) {
        printf("TEST 2.1 - PASSED :)\n");
    }
    else {
        printf("TEST 2.1 - FAILED :(\n");
        free_polar(polar1);
        return 0;
    }

    //test #2: import NACA-4412 polar, generated by XFLR5
    //small formatting errors are present to test the function robustness
    Polar* polar2 = read_xfoil_polar_from_file("02_airfoil_polar_NACA-4412_Re0.030_M0.00_N6.0_EDITED.txt");
    if (polar2->Re == 30000
                && fabs(polar2->alpha[2] - deg2rad(-14.000)) <= 1e-6
                && fabs(polar2->CL[0] + 0.4209) <= 1e-6
                && fabs(polar2->CD[polar2->size-1] - 0.15644) <= 1e-6
                && polar2->size == 61) {
        printf("TEST 2.2 - PASSED :)\n");
    }
    else {
        printf("TEST 2.2 - FAILED :(\n");
        free_polar(polar1);
        free_polar(polar2);
        return 0;
    }

    //test #3: read airfoil using the two previous polars
    const char* filenames3[] = {
        "02_airfoil_polar_NACA-4412_Re0.030_M0.00_N6.0_EDITED.txt",
        "02_airfoil_polar_FX63-120_Re0.300_M0.00_N9.0.txt"
    };
    Airfoil* airfoil3 = import_xfoil_polars(filenames3, 2);
    if (airfoil3->size == 2
                && airfoil3->polars[0]->CL[airfoil3->polars[0]->size-1] == polar2->CL[polar2->size-1]
                && airfoil3->polars[0]->CD[0] == polar2->CD[0]
                && airfoil3->polars[1]->alpha[4] == polar1->alpha[4]) {
        printf("TEST 2.3 - PASSED :)\n");
    }
    else {
        printf("TEST 2.3 - FAILED :(\n");
        free_polar(polar1);
        free_polar(polar2);
        free_airfoil(airfoil3);
        return 0;
    }

    //test #4: generate airfoil using the qprop analytical model
    //NOTE: values taken from the QPROP user guide
    Airfoil* airfoil4 = analytic_polar_curves(
        0.50,       //CL0
        5.8,        //CL_a
        -0.3,       //CLmin
        1.2,        //CLmax
        0.028,      //CD0
        0.050,      //CD2u
        0.020,      //CD2l
        0.5,        //CLCD0
        70000,      //REref
        -0.7        //REexp
    );
    if (airfoil4->size == 7
                && fabs(airfoil4->polars[0]->alpha[0] - deg2rad(-45.0)) <= 1e-6
                && fabs(airfoil4->polars[4]->alpha[30] - deg2rad(+45.0)) <= 1e-6
                && fabs(airfoil4->polars[2]->CL[15] - 0.50) <= 1e-6) {
        printf("TEST 2.4 - PASSED :)\n");
    }
    else {
        printf("TEST 2.4 - FAILED :(\n");
        free_polar(polar1);
        free_polar(polar2);
        free_airfoil(airfoil3);
        free_airfoil(airfoil4);
        return 0;
    }

    //test #5: sort airfoil polars
    const char* filenames5[] = {
        "../webgui/airfoil_polars/naca4412_Ncrit=6/NACA 4412_T1_Re0.200_M0.00_N6.0.txt",
        "../webgui/airfoil_polars/naca4412_Ncrit=6/NACA 4412_T1_Re0.030_M0.00_N6.0.txt",
        "../webgui/airfoil_polars/naca4412_Ncrit=6/NACA 4412_T1_Re0.500_M0.00_N6.0.txt",
        "../webgui/airfoil_polars/naca4412_Ncrit=6/NACA 4412_T1_Re0.100_M0.00_N6.0.txt"
    };
    Airfoil* airfoil5 = import_xfoil_polars(filenames5, 4);
    if (airfoil5->size == 4
                && airfoil5->polars[0]->Re == 30000
                && airfoil5->polars[1]->Re == 100000
                && airfoil5->polars[2]->Re == 200000
                && airfoil5->polars[3]->Re == 500000
                && fabs(airfoil5->polars[0]->CL[airfoil5->polars[0]->size-1] - 1.0065) <= 1e-6
                && fabs(airfoil5->polars[3]->CL[airfoil5->polars[3]->size-1] - 1.5299) <= 1e-6) {
        printf("TEST 2.5 - PASSED :)\n");
    }
    else {
        printf("TEST 2.5 - FAILED :(\n");
        free_polar(polar1);
        free_polar(polar2);
        free_airfoil(airfoil3);
        free_airfoil(airfoil4);
        free_airfoil(airfoil5);
        return 0;
    }

    free_polar(polar1);
    free_polar(polar2);
    free_airfoil(airfoil3);
    free_airfoil(airfoil4);
    free_airfoil(airfoil5);
    return 0;
}
